In [18]:
import pandas as pd
import numpy as np
import seaborn as sns
from matplotlib import pyplot as plt
from matplotlib.pyplot import figure
from sklearn.model_selection import train_test_split
from pandas import ExcelWriter
from pandas import ExcelFile
import glob
import pywt
import sys
import torch

In [9]:
def data_process(data, label):
    CreatData = []
    data = pd.read_csv(data)
    data = data[['Scaled_CAN_ID', 'Time_Gap']].astype('f')
    data["Labele_num"] = np.repeat(label, (len(data)))
    length = len(data)

    X = np.array(data[['Scaled_CAN_ID', 'Time_Gap']])
    y = np.array(data[['Labele_num']])
    strat_time = 0
    timestamp = 10

    for i in range(int(abs(length/10-1))):
        features = X[strat_time:timestamp, :2]
        features = np.reshape(features, (1, 10, 2))
        CreatData.append((features, y[timestamp]))

        strat_time = strat_time + 10
        timestamp = timestamp + 10
        
    return CreatData

In [11]:
input_ = data_process("Tesla_Fuzz_2.csv", 2) # Input Data File Name and Label number (Normal 0, DoS 1, Fuzz 2, Replay 3)

In [12]:
input_[0]

(array([[[2.13e+02, 0.00e+00],
         [2.13e+02, 0.00e+00],
         [2.13e+02, 0.00e+00],
         [2.13e+02, 0.00e+00],
         [2.13e+02, 0.00e+00],
         [2.13e+02, 1.00e-01],
         [2.13e+02, 0.00e+00],
         [2.13e+02, 0.00e+00],
         [2.13e+02, 0.00e+00],
         [2.13e+02, 0.00e+00]]], dtype=float32),
 array([2]))

In [8]:
outout_[0]

array([2])

In [16]:
train_dataset, test_dataset = train_test_split(input_, test_size=0.2)
print("Number of Training Sequences: ", len(train_dataset))
print("Number of Testing Sequences: ", len(test_dataset))

Number of Training Sequences:  19839
Number of Testing Sequences:  4960


In [20]:
batch_size = 64
train_loader = torch.utils.data.DataLoader(train_dataset, batch_size=batch_size,
                                          shuffle=False)

test_loader = torch.utils.data.DataLoader(test_dataset, batch_size=batch_size,
                                         shuffle=False)