In [1]:
%load_ext autoreload
%autoreload 2
import os
import sys
sys.path.append(os.path.abspath('../src/'))
sys.path.append(os.path.abspath('../'))

In [2]:
from src.central_ids import IDS
from src.utils import print_results
from src.dataset import CANDataset
from torch.utils.data import DataLoader
import pytorch_lightning as pl
import numpy as np
from pathlib import Path
from sklearn.metrics import f1_score, confusion_matrix
import pickle
import torch
from flwr.common.parameter import parameters_to_ndarrays
from collections import OrderedDict
from utils import set_parameters, test_model

from pytorch_lightning import loggers
from pytorch_lightning.callbacks import ModelCheckpoint

In [3]:
car_model = 'BMW'
rnd = 50
args = {
    'ckpt_file' : f'../save/FedAvg/train20000_50rnds_15epochs_lr0.0005/ckpt-rnd{rnd}.npz',
    'train_dir': f'../../Data/LISA/{car_model}/train_20000/',
    'val_dir': f'../../Data/LISA/{car_model}/val_10000/',
    'save_dir': f'../save/FedAvg_FN/{car_model}/',
    'C': 2,
    'batch_size': 64,
    'epochs': 10,
    'val_freq': 1,
    'lr': 0.001,
    'weight_decay': 1e-4
}

# Run model from checkpoint

## Kia

In [10]:
train_file = 'train_40000'
ckpt_files = '../save/FedAvg_FN/Kia/lightning_logs/version_5/checkpoints/epoch=08-val_loss=0.00-val_f1=0.9977.ckpt'
fedavg_model = IDS.load_from_checkpoint(ckpt_files, **args)
data_dir = f'../../Data/LISA/Kia/'
print('Training set: ')
print(test_model(Path(data_dir) / train_file, fedavg_model))
print('Test set: ')
print(test_model(Path(data_dir) / 'test_10000', fedavg_model))

Training set: 


GPU available: True (cuda), used: False
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs


Predicting: 0it [00:00, ?it/s]

(array([[28081,     0],
       [    0,  6857]]), (1.0, 1.0, 1.0))
Test set: 


GPU available: True (cuda), used: False
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
/home/dhkim1/miniconda3/envs/torch/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py:1767: PossibleUserWarning: GPU available but not used. Set `accelerator` and `devices` using `Trainer(accelerator='gpu', devices=4)`.
  category=PossibleUserWarning,
/home/dhkim1/miniconda3/envs/torch/lib/python3.7/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:241: PossibleUserWarning: The dataloader, predict_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 32 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  category=PossibleUserWarning,


Predicting: 0it [00:00, ?it/s]

(array([[7189,    2],
       [  27, 2356]]), (0.9991518235793045, 0.9886697440201426, 0.9938831470153976))


## Tesla

In [13]:
ckpt_files = '../save/FedAvg_FN/Tesla/lightning_logs/version_5/checkpoints/epoch=06-val_loss=0.02-val_f1=0.9911.ckpt'
fedavg_model = IDS.load_from_checkpoint(ckpt_files, **args)
data_dir = f'../../Data/LISA/Tesla/'
print('Training set: ')
print(test_model(Path(data_dir) / train_file, fedavg_model))
print('Test set: ')
print(test_model(Path(data_dir) / 'test_10000', fedavg_model))

Training set: 


GPU available: True (cuda), used: False
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
/home/dhkim1/miniconda3/envs/torch/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py:1767: PossibleUserWarning: GPU available but not used. Set `accelerator` and `devices` using `Trainer(accelerator='gpu', devices=4)`.
  category=PossibleUserWarning,
/home/dhkim1/miniconda3/envs/torch/lib/python3.7/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:241: PossibleUserWarning: The dataloader, predict_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 32 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  category=PossibleUserWarning,


Predicting: 0it [00:00, ?it/s]

(array([[31047,     0],
       [    0,  8676]]), (1.0, 1.0, 1.0))
Test set: 


GPU available: True (cuda), used: False
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
/home/dhkim1/miniconda3/envs/torch/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py:1767: PossibleUserWarning: GPU available but not used. Set `accelerator` and `devices` using `Trainer(accelerator='gpu', devices=4)`.
  category=PossibleUserWarning,
/home/dhkim1/miniconda3/envs/torch/lib/python3.7/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:241: PossibleUserWarning: The dataloader, predict_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 32 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  category=PossibleUserWarning,


Predicting: 0it [00:00, ?it/s]

(array([[7765,    1],
       [  37, 2195]]), (0.9995446265938069, 0.9834229390681004, 0.9914182475158085))


## BMW

In [12]:
ckpt_files = '../save/FedAvg_FN/BMW/lightning_logs/version_3/checkpoints/epoch=09-val_loss=0.10-val_f1=0.9509.ckpt'
fedavg_model = IDS.load_from_checkpoint(ckpt_files, **args)
data_dir = f'../../Data/LISA/BMW/'
print('Training set: ')
print(test_model(Path(data_dir) / train_file, fedavg_model))
print('Test set: ')
print(test_model(Path(data_dir) / 'test_10000', fedavg_model))

Training set: 


GPU available: True (cuda), used: False
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
/home/dhkim1/miniconda3/envs/torch/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py:1767: PossibleUserWarning: GPU available but not used. Set `accelerator` and `devices` using `Trainer(accelerator='gpu', devices=4)`.
  category=PossibleUserWarning,
/home/dhkim1/miniconda3/envs/torch/lib/python3.7/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:241: PossibleUserWarning: The dataloader, predict_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 32 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  category=PossibleUserWarning,


Predicting: 0it [00:00, ?it/s]

(array([[29741,   496],
       [  317,  8379]]), (0.944112676056338, 0.9635464581416743, 0.9537305787946047))
Test set: 


GPU available: True (cuda), used: False
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
/home/dhkim1/miniconda3/envs/torch/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py:1767: PossibleUserWarning: GPU available but not used. Set `accelerator` and `devices` using `Trainer(accelerator='gpu', devices=4)`.
  category=PossibleUserWarning,
/home/dhkim1/miniconda3/envs/torch/lib/python3.7/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:241: PossibleUserWarning: The dataloader, predict_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 32 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  category=PossibleUserWarning,


Predicting: 0it [00:00, ?it/s]

(array([[7442,  243],
       [ 108, 2206]]), (0.9007758268681094, 0.9533275713050994, 0.9263069494016376))
